import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import * as repository from '../repositories/plannerRepository.js';
import { ApiError } from '../utils/ApiError.js';

const dayMs=86_400_000;
export const createPlanSchema=z.object({title:z.string().trim().min(2).max(180),subjectId:z.string().uuid(),eventType:z.enum(['exam','quiz','assignment','deadline']),dueAt:z.string().datetime(),coverage:z.string().trim().max(5000).optional(),notes:z.string().trim().max(5000).optional(),lessonIds:z.array(z.string().uuid()).min(1).max(50)}).transform(value=>({...value,lessonIds:[...new Set(value.lessonIds)]}));
export const taskUpdateSchema=z.object({completed:z.boolean()});

export interface RankedLesson extends repository.LessonSignal {priority:number;status:'not_studied'|'weak'|'needs_review'|'good'|'strong'}
export const rankLessons=(lessons:repository.LessonSignal[]):RankedLesson[]=>lessons.map(lesson=>{const status:RankedLesson['status']=lesson.accuracy===null?'not_studied':lesson.accuracy<40?'weak':lesson.accuracy<60?'needs_review':lesson.accuracy<80?'good':'strong';const base=lesson.accuracy===null?100:100-lesson.accuracy;const priority=Math.max(10,Math.min(100,Math.round(base+Math.min(15,lesson.weak_topic_count*5))));return{...lesson,status,priority};}).sort((a,b)=>b.priority-a.priority||a.title.localeCompare(b.title));

const scheduledDates=(count:number,dueAt:Date,now:Date)=>{const usable=Math.max(60*60_000,dueAt.getTime()-now.getTime()-Math.min(12*60*60_000,(dueAt.getTime()-now.getTime())*.1));return Array.from({length:count},(_,index)=>new Date(now.getTime()+usable*((index+1)/(count+1))));};

export const buildSchedule=(lessons:repository.LessonSignal[],eventType:repository.PlanEventType,dueAt:Date,now=new Date()):repository.TaskInput[]=>{const ranked=rankLessons(lessons);const drafts:Array<Omit<repository.TaskInput,'dueAt'|'position'>>=[];for(const lesson of ranked){const weak=lesson.weak_topics.length?` Weak topics: ${lesson.weak_topics.join(', ')}.`:'';if(lesson.status==='not_studied')drafts.push({lessonId:lesson.id,title:`Study ${lesson.title} from the beginning`,taskType:'review',rationale:`No recorded performance yet, so this lesson receives the highest priority.${weak}`,estimatedMinutes:35,priority:lesson.priority});else if(lesson.status==='weak')drafts.push({lessonId:lesson.id,title:`Rebuild ${lesson.title} fundamentals`,taskType:'review',rationale:`Current accuracy is ${Math.round(lesson.accuracy!)}%, classified as weak.${weak}`,estimatedMinutes:35,priority:lesson.priority});else if(lesson.status==='needs_review')drafts.push({lessonId:lesson.id,title:`Review ${lesson.title} with flashcards`,taskType:'flashcards',rationale:`Current accuracy is ${Math.round(lesson.accuracy!)}%, so focused recall should come before another assessment.${weak}`,estimatedMinutes:25,priority:lesson.priority});else drafts.push({lessonId:lesson.id,title:`Take a focused quiz on ${lesson.title}`,taskType:'quiz',rationale:`Current accuracy is ${Math.round(lesson.accuracy!)}%; use a short check to confirm retention.${weak}`,estimatedMinutes:20,priority:lesson.priority});}
  for(const lesson of ranked.filter(item=>item.status==='not_studied'||item.status==='weak'||item.status==='needs_review'))drafts.push({lessonId:lesson.id,title:`Test ${lesson.title} after review`,taskType:'quiz',rationale:'A follow-up check confirms whether the priority review improved recall.',estimatedMinutes:20,priority:Math.max(10,lesson.priority-10)});
  if((eventType==='exam'||eventType==='quiz')&&lessons.length>1)drafts.push({lessonId:null,title:'Complete a cumulative practice exam',taskType:'practice_exam',rationale:'A final mixed assessment checks coverage across every selected lesson before the deadline.',estimatedMinutes:45,priority:55});
  const dates=scheduledDates(drafts.length,dueAt,now);return drafts.map((task,index)=>({...task,position:index+1,dueAt:dates[index]!}));};

const validateDeadline=(dueAt:Date)=>{if(Number.isNaN(dueAt.getTime())||dueAt.getTime()<=Date.now()+60*60_000)throw new ApiError(422,'Choose a deadline at least one hour from now.','PLAN_DEADLINE_INVALID');};
const ownedSignals=async(userId:string,subjectId:string,lessonIds:string[])=>{const signals=await repository.getLessonSignals(userId,subjectId,lessonIds);if(signals.length!==lessonIds.length)throw new ApiError(422,'One or more lessons do not belong to the selected subject.','PLAN_LESSON_INVALID');return signals;};

export const createPlan=async(userId:string,input:z.infer<typeof createPlanSchema>)=>{const dueAt=new Date(input.dueAt);validateDeadline(dueAt);const signals=await ownedSignals(userId,input.subjectId,input.lessonIds);const id=randomUUID();await repository.insertPlan({id,userId,subjectId:input.subjectId,title:input.title,eventType:input.eventType,dueAt,coverage:input.coverage||null,notes:input.notes||null,lessonIds:input.lessonIds,tasks:buildSchedule(signals,input.eventType,dueAt)});return getPlan(userId,id);};
export const listPlans=(userId:string)=>repository.listPlans(userId);
export const getPlan=async(userId:string,id:string)=>{const plan=await repository.findPlan(id,userId);if(!plan)throw new ApiError(404,'Study plan not found.','PLAN_NOT_FOUND');const lessonIds=await repository.getPlanLessonIds(id);const signals=plan.subject_id?await repository.getLessonSignals(userId,plan.subject_id,lessonIds):[];return{plan,tasks:await repository.getTasks(id),priorities:rankLessons(signals)};};
export const regenerate=async(userId:string,id:string)=>{const detail=await getPlan(userId,id);validateDeadline(new Date(detail.plan.due_at));await repository.replacePendingTasks(id,buildSchedule(detail.priorities,detail.plan.event_type,new Date(detail.plan.due_at)));return getPlan(userId,id);};
export const completeTask=async(userId:string,planId:string,taskId:string,completed:boolean)=>{if(!await repository.setTaskCompleted({planId,taskId,userId,completed}))throw new ApiError(404,'Study task not found.','TASK_NOT_FOUND');return getPlan(userId,planId);};
export const removePlan=async(userId:string,id:string)=>{if(!await repository.deletePlan(id,userId))throw new ApiError(404,'Study plan not found.','PLAN_NOT_FOUND');};
export const daysRemaining=(dueAt:Date,now=new Date())=>Math.max(0,Math.ceil((dueAt.getTime()-now.getTime())/dayMs));
