import { createHash, randomUUID } from 'node:crypto';
import { z } from 'zod';
import * as repository from '../repositories/quizRepository.js';
import { quizJsonSchema, quizOutputSchema, generateStructured } from './aiService.js';
import { getLessonSource } from './studyContentService.js';
import * as usage from './usageService.js';
import { ApiError } from '../utils/ApiError.js';
import { classifyAccuracy } from './progressRules.js';

export const quizGenerationInputSchema=z.object({lessonId:z.string().uuid(),count:z.number().int().min(5).max(100),questionType:z.enum(['multiple_choice','true_false','identification','mixed']),difficulty:z.enum(['easy','medium','hard']),regenerate:z.boolean().default(false)});
export const quizSubmissionSchema=z.object({startedAt:z.string().datetime(),answers:z.array(z.object({questionId:z.string().uuid(),answer:z.string().max(2000)})).max(100)}).superRefine((value,context)=>{if(new Set(value.answers.map(answer=>answer.questionId)).size!==value.answers.length)context.addIssue({code:z.ZodIssueCode.custom,message:'Each question may only be answered once.'});});
const keyFor=(sourceVersion:string,options:unknown)=>createHash('sha256').update(JSON.stringify({sourceVersion,kind:'quiz',options})).digest('hex');
export const normalizeAnswer=(value:string)=>value.normalize('NFKC').trim().toLocaleLowerCase().replace(/\s+/g,' ').replace(/[.!?]+$/,'');
export { classifyAccuracy } from './progressRules.js';
export const scoreQuestions=(questions:repository.StoredQuestion[],submitted:Array<{questionId:string;answer:string}>)=>{const byId=new Map(submitted.map(answer=>[answer.questionId,answer.answer]));const answers=questions.map(question=>{const answer=byId.get(question.id)??'';const accepted=[question.correct_answer,...question.acceptable_answers].map(normalizeAnswer);return{questionId:question.id,topicId:question.topic_id,topic:question.topic,answer,isCorrect:accepted.includes(normalizeAnswer(answer))};});const correctCount=answers.filter(answer=>answer.isCorrect).length;const percentage=questions.length?Number((correctCount/questions.length*100).toFixed(2)):0;const topicMap=new Map<string,{topic:string;correct:number;total:number}>();for(const answer of answers){const key=answer.topicId??answer.topic??'untagged';const current=topicMap.get(key)??{topic:answer.topic??'Other',correct:0,total:0};current.total+=1;if(answer.isCorrect)current.correct+=1;topicMap.set(key,current);}const topics=[...topicMap.values()].map(topic=>{const accuracy=Number((topic.correct/topic.total*100).toFixed(2));return{...topic,accuracy,status:classifyAccuracy(accuracy)};});return{correctCount,totalCount:questions.length,percentage,answers,topics};};

export const generateQuiz=async(userId:string,input:z.infer<typeof quizGenerationInputSchema>)=>{const source=await getLessonSource(input.lessonId,userId);const options={count:input.count,questionType:input.questionType,difficulty:input.difficulty};const generationKey=keyFor(source.sourceVersion,options);if(!input.regenerate){const cached=await repository.findCachedQuiz(input.lessonId,userId,generationKey);if(cached)return{...cached,question_count:Number(cached.question_count),cached:true};}await usage.assertQuota(userId,'quiz');try{const typeDirection=input.questionType==='mixed'?'Use a balanced mix of multiple_choice, true_false, and identification questions.':`Use only ${input.questionType} questions.`;const result=await generateStructured({prompt:`Create exactly ${input.count} ${input.difficulty} quiz questions for the lesson "${source.title}". ${typeDirection} Every question and explanation must be explicitly supported by the lesson context. For multiple_choice, provide exactly four choices and set correctAnswer to the exact correct choice text. For true_false, use an empty choices array and set correctAnswer to "True" or "False". For identification, use an empty choices array and include reasonable equivalent responses in acceptableAnswers. Assign one concise topic to every question. Avoid duplicates.\n\nLESSON CONTEXT:\n${source.context}`,jsonSchema:quizJsonSchema,validator:quizOutputSchema,maxOutputTokens:Math.min(16000,1500+input.count*350)});if(result.data.questions.length!==input.count)throw new ApiError(502,`Gemini returned ${result.data.questions.length} questions instead of ${input.count}. Please try again.`,'AI_QUESTION_COUNT_MISMATCH');if(input.questionType!=='mixed'&&result.data.questions.some(question=>question.questionType!==input.questionType))throw new ApiError(502,'Gemini returned an unexpected question type. Please try again.','AI_QUESTION_TYPE_MISMATCH');const questions=result.data.questions.map(question=>({...question,acceptableAnswers:question.acceptableAnswers??[]}));const id=randomUUID();await repository.insertQuiz({id,lessonId:input.lessonId,title:result.data.title,questionType:input.questionType,difficulty:input.difficulty,sourceVersion:source.sourceVersion,generationKey,questions});await usage.logSuccess(userId,'quiz',result);return{...(await repository.findCachedQuiz(input.lessonId,userId,generationKey))!,question_count:input.count,cached:false};}catch(error){await usage.logFailure(userId,'quiz',error instanceof ApiError?error.code:'AI_UNKNOWN').catch(()=>undefined);throw error;}};

export const getQuiz=async(userId:string,quizId:string)=>{const quiz=await repository.getQuiz(quizId,userId);if(!quiz)throw new ApiError(404,'Quiz not found.','QUIZ_NOT_FOUND');return quiz;};
export const submitQuiz=async(userId:string,quizId:string,input:z.infer<typeof quizSubmissionSchema>)=>{const owned=await repository.getQuiz(quizId,userId);if(!owned)throw new ApiError(404,'Quiz not found.','QUIZ_NOT_FOUND');const questions=await repository.getQuestions(quizId);const validIds=new Set(questions.map(question=>question.id));if(input.answers.some(answer=>!validIds.has(answer.questionId)))throw new ApiError(422,'One or more answers do not belong to this quiz.','INVALID_QUIZ_ANSWER');const score=scoreQuestions(questions,input.answers);const id=randomUUID();const startedAt=new Date(input.startedAt);const endedAt=new Date();const durationSeconds=Math.max(0,Math.min(14_400,Math.round((endedAt.getTime()-startedAt.getTime())/1000)));await repository.insertAttempt({id,quizId,lessonId:owned.quiz.lesson_id,userId,startedAt,endedAt,durationSeconds,correctCount:score.correctCount,totalCount:score.totalCount,percentage:score.percentage,answers:score.answers});return{...(await repository.getAttempt(id,userId))!,topics:score.topics};};
export const getAttempt=async(userId:string,attemptId:string)=>{const attempt=await repository.getAttempt(attemptId,userId);if(!attempt)throw new ApiError(404,'Quiz attempt not found.','ATTEMPT_NOT_FOUND');const topicMap=new Map<string,{topic:string;correct:number;total:number}>();for(const answer of attempt.answers){const key=answer.topic??'Other';const current=topicMap.get(key)??{topic:key,correct:0,total:0};current.total+=1;if(answer.is_correct)current.correct+=1;topicMap.set(key,current);}return{...attempt,topics:[...topicMap.values()].map(topic=>{const accuracy=Number((topic.correct/topic.total*100).toFixed(2));return{...topic,accuracy,status:classifyAccuracy(accuracy)};})};};
