import { randomUUID } from 'node:crypto';
import type { ResultSetHeader, RowDataPacket } from '../config/database.js';
import { db } from '../config/database.js';
import type { QuizOutput } from '../services/aiService.js';
import { recordStudySession } from './progressRepository.js';

export type QuizQuestionType='multiple_choice'|'true_false'|'identification';
export type QuizConfigurationType=QuizQuestionType|'mixed';
export type QuizDifficulty='easy'|'medium'|'hard';
export interface QuizRecord {id:string;lesson_id:string;title:string;question_type:QuizConfigurationType;difficulty:QuizDifficulty;question_count:number;source_version:string;generation_key:string;created_at:Date;updated_at:Date;lesson_title?:string;subject_name?:string;attempt_count?:number;best_percentage?:number|null;latest_percentage?:number|null}
export interface StoredQuestion {id:string;quiz_id:string;topic_id:string|null;topic:string|null;position:number;question_type:QuizQuestionType;prompt:string;choices:string[];correct_answer:string;acceptable_answers:string[];explanation:string}

const jsonValue=<T>(value:unknown):T=>typeof value==='string'?JSON.parse(value) as T:value as T;

export const findCachedQuiz=async(lessonId:string,userId:string,generationKey:string)=>{const [rows]=await db.query<(RowDataPacket&QuizRecord)[]>(`SELECT q.* FROM quizzes q JOIN lessons l ON l.id=q.lesson_id JOIN subjects s ON s.id=l.subject_id WHERE q.lesson_id=? AND s.user_id=? AND q.generation_key=? ORDER BY q.created_at DESC LIMIT 1`,[lessonId,userId,generationKey]);return rows[0]??null;};

export const insertQuiz=async(input:{id:string;lessonId:string;title:string;questionType:QuizConfigurationType;difficulty:QuizDifficulty;sourceVersion:string;generationKey:string;questions:QuizOutput['questions']})=>{const connection=await db.getConnection();try{await connection.beginTransaction();await connection.execute(`INSERT INTO quizzes (id,lesson_id,title,question_type,difficulty,question_count,source_version,generation_key) VALUES (?,?,?,?,?,?,?,?)`,[input.id,input.lessonId,input.title,input.questionType,input.difficulty,input.questions.length,input.sourceVersion,input.generationKey]);for(const [index,question] of input.questions.entries()){const [existing]=await connection.query<(RowDataPacket&{id:string})[]>('SELECT id FROM topics WHERE lesson_id=? AND name=? LIMIT 1',[input.lessonId,question.topic]);let topicId=existing[0]?.id;if(!topicId){topicId=randomUUID();await connection.execute('INSERT INTO topics (id,lesson_id,name) VALUES (?,?,?) ON CONFLICT (lesson_id,name) DO NOTHING',[topicId,input.lessonId,question.topic]);const [resolved]=await connection.query<(RowDataPacket&{id:string})[]>('SELECT id FROM topics WHERE lesson_id=? AND name=? LIMIT 1',[input.lessonId,question.topic]);topicId=resolved[0]!.id;}await connection.execute(`INSERT INTO quiz_questions (id,quiz_id,topic_id,position,question_type,prompt,choices_json,correct_answer_json,explanation) VALUES (?,?,?,?,?,?,?,?,?)`,[randomUUID(),input.id,topicId,index+1,question.questionType,question.prompt,JSON.stringify(question.choices),JSON.stringify({answer:question.correctAnswer,acceptableAnswers:question.acceptableAnswers}),question.explanation]);}await connection.commit();}catch(error){await connection.rollback();throw error;}finally{connection.release();}};

export const listQuizzes=async(userId:string,lessonId?:string)=>{const values:string[]=[userId];const filter=lessonId?' AND q.lesson_id=?':'';if(lessonId)values.push(lessonId);const [rows]=await db.query<(RowDataPacket&QuizRecord)[]>(`SELECT q.*,l.title lesson_title,s.name subject_name,(SELECT COUNT(*) FROM quiz_attempts qa WHERE qa.quiz_id=q.id AND qa.user_id=?) attempt_count,(SELECT MAX(qa.percentage) FROM quiz_attempts qa WHERE qa.quiz_id=q.id AND qa.user_id=?) best_percentage,(SELECT qa.percentage FROM quiz_attempts qa WHERE qa.quiz_id=q.id AND qa.user_id=? ORDER BY qa.completed_at DESC LIMIT 1) latest_percentage FROM quizzes q JOIN lessons l ON l.id=q.lesson_id JOIN subjects s ON s.id=l.subject_id WHERE s.user_id=?${filter} ORDER BY q.updated_at DESC`,[userId,userId,userId,...values]);return rows.map(row=>({...row,question_count:Number(row.question_count),attempt_count:Number(row.attempt_count??0),best_percentage:row.best_percentage===null?null:Number(row.best_percentage),latest_percentage:row.latest_percentage===null?null:Number(row.latest_percentage)}));};

export const getQuiz=async(quizId:string,userId:string)=>{const [quizzes]=await db.query<(RowDataPacket&QuizRecord)[]>(`SELECT q.*,l.title lesson_title,s.name subject_name FROM quizzes q JOIN lessons l ON l.id=q.lesson_id JOIN subjects s ON s.id=l.subject_id WHERE q.id=? AND s.user_id=? LIMIT 1`,[quizId,userId]);const quiz=quizzes[0];if(!quiz)return null;const questions=await getQuestions(quizId);return{quiz:{...quiz,question_count:Number(quiz.question_count)},questions:questions.map(({correct_answer:_,acceptable_answers:__,explanation:___,...question})=>question)};};

export const getQuestions=async(quizId:string)=>{const [rows]=await db.query<(RowDataPacket&{id:string;quiz_id:string;topic_id:string|null;topic:string|null;position:number;question_type:QuizQuestionType;prompt:string;choices_json:unknown;correct_answer_json:unknown;explanation:string})[]>(`SELECT qq.*,t.name topic FROM quiz_questions qq LEFT JOIN topics t ON t.id=qq.topic_id WHERE qq.quiz_id=? ORDER BY qq.position`,[quizId]);return rows.map(row=>{const answer=jsonValue<{answer:string;acceptableAnswers?:string[]}>(row.correct_answer_json);return{id:row.id,quiz_id:row.quiz_id,topic_id:row.topic_id,topic:row.topic,position:Number(row.position),question_type:row.question_type,prompt:row.prompt,choices:jsonValue<string[]>(row.choices_json??[]),correct_answer:answer.answer,acceptable_answers:answer.acceptableAnswers??[],explanation:row.explanation};});};

export const insertAttempt=async(input:{id:string;quizId:string;lessonId:string;userId:string;startedAt:Date;endedAt:Date;durationSeconds:number;correctCount:number;totalCount:number;percentage:number;answers:Array<{questionId:string;topicId:string|null;answer:string;isCorrect:boolean}>})=>{const connection=await db.getConnection();try{await connection.beginTransaction();await connection.execute(`INSERT INTO quiz_attempts (id,quiz_id,user_id,correct_count,total_count,percentage,started_at,completed_at) VALUES (?,?,?,?,?,?,?,?)`,[input.id,input.quizId,input.userId,input.correctCount,input.totalCount,input.percentage,input.startedAt,input.endedAt]);for(const answer of input.answers){await connection.execute(`INSERT INTO quiz_answers (id,attempt_id,question_id,answer_json,is_correct) VALUES (?,?,?,?,?)`,[randomUUID(),input.id,answer.questionId,JSON.stringify({value:answer.answer}),answer.isCorrect]);if(answer.topicId)await connection.execute(`INSERT INTO topic_performance (id,user_id,topic_id,correct_answers,total_answers) VALUES (gen_random_uuid(),?,?,?,1) ON CONFLICT (user_id,topic_id) DO UPDATE SET correct_answers=topic_performance.correct_answers+EXCLUDED.correct_answers,total_answers=topic_performance.total_answers+1`,[input.userId,answer.topicId,answer.isCorrect?1:0]);}await recordStudySession({userId:input.userId,lessonId:input.lessonId,activityType:'quiz',startedAt:input.startedAt,endedAt:input.endedAt,durationSeconds:input.durationSeconds},connection);await connection.commit();}catch(error){await connection.rollback();throw error;}finally{connection.release();}};

export const getAttempt=async(attemptId:string,userId:string)=>{const [attempts]=await db.query<(RowDataPacket&{id:string;quiz_id:string;quiz_title:string;lesson_id:string;lesson_title:string;correct_count:number;total_count:number;percentage:number;started_at:Date;completed_at:Date})[]>(`SELECT qa.id,qa.quiz_id,q.title quiz_title,q.lesson_id,l.title lesson_title,qa.correct_count,qa.total_count,qa.percentage,qa.started_at,qa.completed_at FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id JOIN lessons l ON l.id=q.lesson_id WHERE qa.id=? AND qa.user_id=? LIMIT 1`,[attemptId,userId]);const attempt=attempts[0];if(!attempt)return null;const [rows]=await db.query<(RowDataPacket&{question_id:string;position:number;prompt:string;question_type:QuizQuestionType;choices_json:unknown;answer_json:unknown;is_correct:number;correct_answer_json:unknown;explanation:string;topic:string|null})[]>(`SELECT ans.question_id,qq.position,qq.prompt,qq.question_type,qq.choices_json,ans.answer_json,ans.is_correct,qq.correct_answer_json,qq.explanation,t.name topic FROM quiz_answers ans JOIN quiz_questions qq ON qq.id=ans.question_id LEFT JOIN topics t ON t.id=qq.topic_id WHERE ans.attempt_id=? ORDER BY qq.position`,[attemptId]);return{attempt:{...attempt,correct_count:Number(attempt.correct_count),total_count:Number(attempt.total_count),percentage:Number(attempt.percentage)},answers:rows.map(row=>{const correct=jsonValue<{answer:string;acceptableAnswers?:string[]}>(row.correct_answer_json);return{question_id:row.question_id,position:Number(row.position),prompt:row.prompt,question_type:row.question_type,choices:jsonValue<string[]>(row.choices_json??[]),answer:jsonValue<{value:string}>(row.answer_json).value,is_correct:Boolean(row.is_correct),correct_answer:correct.answer,acceptable_answers:correct.acceptableAnswers??[],explanation:row.explanation,topic:row.topic};})};};

export const deleteQuiz=async(quizId:string,userId:string)=>{const [result]=await db.execute<ResultSetHeader>(`DELETE FROM quizzes WHERE id=? AND EXISTS (SELECT 1 FROM lessons l JOIN subjects s ON s.id=l.subject_id WHERE l.id=quizzes.lesson_id AND s.user_id=?)`,[quizId,userId]);return result.affectedRows>0;};
