import { randomUUID } from 'node:crypto';
import type { RowDataPacket } from '../config/database.js';
import { db } from '../config/database.js';

export const listAvailableLessons=async(userId:string)=>{const [rows]=await db.query<(RowDataPacket&{id:string;title:string;subject_name:string})[]>(`SELECT DISTINCT l.id,l.title,s.name subject_name FROM lessons l JOIN subjects s ON s.id=l.subject_id JOIN documents d ON d.lesson_id=l.id AND d.status='ready' WHERE s.user_id=? ORDER BY s.name,l.title`,[userId]);return rows;};
export const createConversation=async(input:{id:string;userId:string;lessonId:string;title:string})=>db.execute(`INSERT INTO tutor_conversations (id,user_id,lesson_id,title) VALUES (?,?,?,?)`,[input.id,input.userId,input.lessonId,input.title]);
export const findConversation=async(id:string,userId:string)=>{const [rows]=await db.query<(RowDataPacket&{id:string;lesson_id:string;title:string;lesson_title:string;subject_name:string;created_at:Date;updated_at:Date})[]>(`SELECT tc.id,tc.lesson_id,tc.title,l.title lesson_title,s.name subject_name,tc.created_at,tc.updated_at FROM tutor_conversations tc JOIN lessons l ON l.id=tc.lesson_id JOIN subjects s ON s.id=l.subject_id WHERE tc.id=? AND tc.user_id=? LIMIT 1`,[id,userId]);return rows[0]??null;};
export const listConversations=async(userId:string)=>{const [rows]=await db.query<(RowDataPacket&{id:string;lesson_id:string;title:string;lesson_title:string;subject_name:string;updated_at:Date})[]>(`SELECT tc.id,tc.lesson_id,tc.title,l.title lesson_title,s.name subject_name,tc.updated_at FROM tutor_conversations tc JOIN lessons l ON l.id=tc.lesson_id JOIN subjects s ON s.id=l.subject_id WHERE tc.user_id=? ORDER BY tc.updated_at DESC`,[userId]);return rows;};
export const insertMessage=async(input:{conversationId:string;role:'user'|'assistant';content:string;sources?:unknown})=>{const id=randomUUID();await db.execute(`INSERT INTO tutor_messages (id,conversation_id,role,content,sources_json) VALUES (?,?,?,?,?)`,[id,input.conversationId,input.role,input.content,input.sources?JSON.stringify(input.sources):null]);await db.execute('UPDATE tutor_conversations SET updated_at=CURRENT_TIMESTAMP WHERE id=?',[input.conversationId]);return id;};
export const listMessages=async(conversationId:string,limit=100)=>{const [rows]=await db.query<(RowDataPacket&{id:string;role:'user'|'assistant';content:string;sources_json:unknown;created_at:Date})[]>(`SELECT id,role,content,sources_json,created_at FROM tutor_messages WHERE conversation_id=? ORDER BY created_at DESC LIMIT ?`,[conversationId,limit]);return rows.reverse().map(row=>({...row,sources:typeof row.sources_json==='string'?JSON.parse(row.sources_json):row.sources_json??[]}));};
