import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';

interface InstallPromptEvent extends Event {prompt():Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed';platform:string}>}
interface PwaValue {isOnline:boolean;isInstalled:boolean;canInstall:boolean;updateReady:boolean;showInstallHint:boolean;install():Promise<void>;applyUpdate():void;dismissInstallHint():void}
const PwaContext=createContext<PwaValue|null>(null);

export function PwaProvider({children}:{children:ReactNode}){const [isOnline,setOnline]=useState(navigator.onLine);const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);const [showInstallHint,setShowInstallHint]=useState(false);const [updateReady,setUpdateReady]=useState(false);const [registration,setRegistration]=useState<ServiceWorkerRegistration|null>(null);const refreshing=useRef(false);const standalone=window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);const isIos=/iphone|ipad|ipod/i.test(navigator.userAgent);
  useEffect(()=>{const online=()=>setOnline(true),offline=()=>setOnline(false),beforeInstall=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent);};window.addEventListener('online',online);window.addEventListener('offline',offline);window.addEventListener('beforeinstallprompt',beforeInstall);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',offline);window.removeEventListener('beforeinstallprompt',beforeInstall);};},[]);
  useEffect(()=>{if(!import.meta.env.PROD||!('serviceWorker' in navigator))return;let interval=0;navigator.serviceWorker.register('/sw.js').then(value=>{setRegistration(value);if(value.waiting)setUpdateReady(true);value.addEventListener('updatefound',()=>{const worker=value.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)setUpdateReady(true);});});interval=window.setInterval(()=>void value.update(),60*60_000);}).catch(()=>undefined);const changed=()=>{if(refreshing.current)window.location.reload();};navigator.serviceWorker.addEventListener('controllerchange',changed);return()=>{if(interval)window.clearInterval(interval);navigator.serviceWorker.removeEventListener('controllerchange',changed);};},[]);
  const value=useMemo<PwaValue>(()=>({isOnline,isInstalled:standalone,canInstall:(Boolean(installPrompt)||isIos)&&!standalone,updateReady,showInstallHint,async install(){if(!installPrompt){if(isIos)setShowInstallHint(true);return;}await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);},applyUpdate(){if(!registration?.waiting)return;refreshing.current=true;registration.waiting.postMessage({type:'SKIP_WAITING'});},dismissInstallHint(){setShowInstallHint(false);}}),[isOnline,standalone,installPrompt,isIos,updateReady,showInstallHint,registration]);return <PwaContext.Provider value={value}>{children}</PwaContext.Provider>;
}
export const usePwa=()=>{const value=useContext(PwaContext);if(!value)throw new Error('usePwa must be used within PwaProvider');return value;};

export function PwaStatus(){const {isOnline,updateReady,showInstallHint,applyUpdate,dismissInstallHint}=usePwa();return <>{!isOnline&&<div role="status" className="fixed inset-x-0 bottom-4 z-[70] mx-auto flex w-fit items-center gap-2 rounded-full bg-slate-950 px-4 py-2 text-xs font-bold text-white shadow-float dark:bg-white dark:text-slate-950"><span className="size-2 rounded-full bg-amber-400"/>Offline mode · showing saved content where available</div>}{showInstallHint&&<div role="status" className="fixed bottom-4 left-4 right-4 z-[71] mx-auto flex max-w-md items-center justify-between gap-4 rounded-2xl bg-ink p-4 text-white shadow-float"><div><strong className="block text-sm">Install on iPhone or iPad</strong><span className="text-xs text-slate-300">Tap Share in Safari, then choose Add to Home Screen.</span></div><button onClick={dismissInstallHint} className="shrink-0 rounded-xl border border-white/20 px-3 py-2 text-xs font-extrabold">Got it</button></div>}{updateReady&&<div role="status" className="fixed bottom-4 left-4 right-4 z-[72] mx-auto flex max-w-md items-center justify-between gap-4 rounded-2xl bg-ink p-4 text-white shadow-float"><div><strong className="block text-sm">Update ready</strong><span className="text-xs text-slate-300">Reload to use the latest StudyMate version.</span></div><button onClick={applyUpdate} className="shrink-0 rounded-xl bg-white px-3 py-2 text-xs font-extrabold text-ink">Update</button></div>}</>;
}
