import { z } from 'zod';
import * as repository from '../repositories/progressRepository.js';
import { classifyAccuracy, recommendationFor } from './progressRules.js';

export const offsetSchema=z.coerce.number().int().min(-840).max(840).default(0);
const dayMs=86_400_000;
const dateKey=(date:Date,offsetMinutes:number)=>new Date(date.getTime()+offsetMinutes*60_000).toISOString().slice(0,10);
const ordinal=(key:string)=>Date.parse(`${key}T00:00:00.000Z`)/dayMs;

export const calculateStreaks=(dates:string[],todayKey:string)=>{const days=[...new Set(dates)].sort((a,b)=>ordinal(a)-ordinal(b));let best=0;let run=0;let previous:number|null=null;for(const day of days){const value=ordinal(day);run=previous!==null&&value-previous===1?run+1:1;best=Math.max(best,run);previous=value;}const today=ordinal(todayKey);const latest=days.length?ordinal(days[days.length-1]!):null;if(latest===null||today-latest>1)return{current:0,best};let current=1;for(let index=days.length-2;index>=0;index-=1){if(ordinal(days[index+1]!)-ordinal(days[index]!)!==1)break;current+=1;}return{current,best};};

export const getOverview=async(userId:string,offsetMinutes:number)=>{const [metrics,topicRows,subjects,quizTrend,recentLessons,actionRows,minuteRows,activityDates]=await Promise.all([repository.getMetricTotals(userId),repository.getTopicPerformance(userId),repository.getSubjectPerformance(userId),repository.getQuizTrend(userId),repository.getRecentLessons(userId),repository.getWeeklyActions(userId,offsetMinutes),repository.getWeeklyMinutes(userId,offsetMinutes),repository.getActivityDates(userId,offsetMinutes)]);const actions=new Map(actionRows.map(row=>[row.day,row.actions]));const minutes=new Map(minuteRows.map(row=>[row.day,row.minutes]));const today=new Date();const weeklyActivity=Array.from({length:7},(_,index)=>{const date=new Date(today.getTime()-(6-index)*dayMs);const key=dateKey(date,offsetMinutes);return{date:key,label:new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(new Date(`${key}T00:00:00.000Z`)),minutes:minutes.get(key)??0,actions:actions.get(key)??0};});const streak=calculateStreaks(activityDates,dateKey(today,offsetMinutes));const topics=topicRows.map(row=>{const status=classifyAccuracy(row.accuracy);return{...row,status,recommendation:recommendationFor({topic:row.topic,status,lessonId:row.lesson_id})};});return{metrics:{...metrics,current_streak:streak.current,best_streak:streak.best},weekly_activity:weeklyActivity,topics,subjects,quiz_trend:quizTrend,recent_lessons:recentLessons,recommendation:topics[0]?.recommendation??{title:'Take your first practice quiz',description:'Complete a grounded quiz to unlock topic-level recommendations.',action:'Browse subjects',href:'/app/subjects'}};};
