import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import * as aiRepository from '../repositories/aiRepository.js';
import * as repository from '../repositories/tutorRepository.js';
import { recordStudySession } from '../repositories/progressRepository.js';
import { ApiError } from '../utils/ApiError.js';
import { generateGroundedText } from './aiService.js';
import * as usage from './usageService.js';

export const messageInputSchema=z.object({lessonId:z.string().uuid(),conversationId:z.string().uuid().optional(),question:z.string().trim().min(2).max(2000)});
const terms=(text:string)=>[...new Set(text.toLowerCase().match(/[a-z0-9]{3,}/g)??[])];
export const rankChunks=(question:string,chunks:aiRepository.SourceChunk[])=>{const query=terms(question);return chunks.map(chunk=>{const haystack=`${chunk.heading??''} ${chunk.content}`.toLowerCase();const score=query.reduce((sum,term)=>sum+(haystack.match(new RegExp(`\\b${term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'g'))?.length??0),0);return{chunk,score};}).sort((a,b)=>b.score-a.score||a.chunk.chunk_index-b.chunk.chunk_index).slice(0,Math.min(5,chunks.length)).map(item=>item.chunk);};
export const ask=async(userId:string,input:z.infer<typeof messageInputSchema>)=>{const chunks=await aiRepository.getLessonSourceChunks(input.lessonId,userId);if(!chunks.length)throw new ApiError(409,'Upload and process lesson material before using the tutor.','LESSON_CONTENT_REQUIRED');let conversation=input.conversationId?await repository.findConversation(input.conversationId,userId):null;if(input.conversationId&&!conversation)throw new ApiError(404,'Tutor conversation not found.','CONVERSATION_NOT_FOUND');if(conversation&&conversation.lesson_id!==input.lessonId)throw new ApiError(422,'The conversation belongs to another lesson.','CONVERSATION_LESSON_MISMATCH');if(!conversation){const id=randomUUID();await repository.createConversation({id,userId,lessonId:input.lessonId,title:input.question.slice(0,80)});conversation=await repository.findConversation(id,userId);}const relevant=rankChunks(input.question,chunks);const history=(await repository.listMessages(conversation!.id,10)).map(message=>`${message.role.toUpperCase()}: ${message.content}`).join('\n');await usage.assertQuota(userId,'tutor');await repository.insertMessage({conversationId:conversation!.id,role:'user',content:input.question});try{const result=await generateGroundedText(`Answer the student's question only from the quoted lesson excerpts. If the answer is not present, say the uploaded lesson does not contain enough information. Cite excerpts inline as [Source 1], [Source 2], and so on when useful.\n\nRECENT CONVERSATION:\n${history||'(none)'}\n\nLESSON EXCERPTS:\n${relevant.map((chunk,index)=>`[Source ${index+1}: ${chunk.document_name}${chunk.page_number?`, page/slide ${chunk.page_number}`:''}]\n${chunk.content}`).join('\n\n')}\n\nSTUDENT QUESTION:\n${input.question}`);const sources=relevant.map((chunk,index)=>({number:index+1,document:chunk.document_name,page:chunk.page_number,heading:chunk.heading}));await repository.insertMessage({conversationId:conversation!.id,role:'assistant',content:result.text,sources});await usage.logSuccess(userId,'tutor',result);const now=new Date();await recordStudySession({userId,lessonId:input.lessonId,activityType:'tutor',startedAt:now,endedAt:now,durationSeconds:0});return{conversation:conversation!,message:{role:'assistant',content:result.text,sources}};}catch(error){await usage.logFailure(userId,'tutor',error instanceof ApiError?error.code:'AI_UNKNOWN').catch(()=>undefined);throw error;}};
export const getConversation=async(userId:string,id:string)=>{const conversation=await repository.findConversation(id,userId);if(!conversation)throw new ApiError(404,'Tutor conversation not found.','CONVERSATION_NOT_FOUND');return{conversation,messages:await repository.listMessages(id)};};
