import { Router } from 'express';
import { authRouter } from './authRoutes.js';
import { lessonRouter } from './lessonRoutes.js';
import { subjectRouter } from './subjectRoutes.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { getDashboard } from '../controllers/dashboardController.js';
import { documentRouter } from './documentRoutes.js';
import { aiRouter } from './aiRoutes.js';
import * as aiController from '../controllers/aiController.js';
import { flashcardDeckRouter, flashcardRouter } from './flashcardRoutes.js';
import { quizAttemptRouter, quizRouter } from './quizRoutes.js';
import { progressRouter } from './progressRoutes.js';
import { tutorRouter } from './tutorRoutes.js';
import { examRouter } from './examRoutes.js';
import { plannerRouter } from './plannerRoutes.js';
import { searchRouter } from './searchRoutes.js';

export const apiRouter = Router();
apiRouter.get('/health', (_request, response) => response.json({ success: true, data: { status: 'healthy', timestamp: new Date().toISOString() } }));
apiRouter.use('/auth', authRouter);
apiRouter.use('/subjects', subjectRouter);
apiRouter.use('/lessons', lessonRouter);
apiRouter.use('/documents', documentRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.get('/reviewers', requireAuth, asyncHandler(aiController.listReviewers));
apiRouter.get('/summaries', requireAuth, asyncHandler(aiController.listSummaries));
apiRouter.use('/flashcard-decks',flashcardDeckRouter);
apiRouter.use('/flashcards',flashcardRouter);
apiRouter.use('/quizzes',quizRouter);
apiRouter.use('/quiz-attempts',quizAttemptRouter);
apiRouter.use('/progress',progressRouter);
apiRouter.use('/tutor',tutorRouter);
apiRouter.use('/exams',examRouter);
apiRouter.use('/study-plans',plannerRouter);
apiRouter.use('/search',searchRouter);
apiRouter.get('/dashboard', requireAuth, asyncHandler(getDashboard));
