import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, LoaderCircle, Sparkles } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Logo } from '../components/ui/Logo';
import { apiMessage } from '../lib/api';
import { useAuth } from '../store/AuthContext';

function AuthFrame({ children, title, subtitle }: { children: React.ReactNode; title: string; subtitle: string }) {
  return <div className="grid min-h-screen lg:grid-cols-[1fr_1.05fr]"><aside className="relative hidden overflow-hidden bg-ink p-12 text-white lg:flex lg:flex-col"><div className="absolute -right-20 -top-20 size-80 rounded-full bg-brand-500/20 blur-3xl"/><Logo className="relative [&_span:last-child]:text-white"/><div className="relative my-auto max-w-lg"><div className="mb-6 grid size-12 place-items-center rounded-2xl bg-brand-500/20 text-brand-200"><Sparkles size={23}/></div><blockquote className="font-display text-3xl font-bold leading-[1.35]">“Success is the sum of small efforts, repeated day in and day out.”</blockquote><p className="mt-5 text-sm font-semibold text-slate-400">— Robert Collier</p><div className="mt-12 grid grid-cols-3 gap-3">{[['24','Lessons'],['78%','Accuracy'],['7 days','Streak']].map(([v,l])=><div className="rounded-2xl border border-white/10 bg-white/5 p-4" key={l}><div className="text-lg font-extrabold">{v}</div><div className="mt-1 text-xs text-slate-400">{l}</div></div>)}</div></div><p className="relative text-xs text-slate-500">A calm place to turn effort into progress.</p></aside><main className="relative flex items-center justify-center bg-white px-5 py-12 dark:bg-slate-950 sm:px-10"><Link to="/" className="absolute left-5 top-6 flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900 dark:hover:text-white sm:left-8"><ArrowLeft size={16}/> Home</Link><div className="w-full max-w-md"><Logo className="mb-10 lg:hidden"/><p className="eyebrow">Welcome to StudyMate</p><h1 className="mt-3 font-display text-3xl font-extrabold tracking-tight">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{subtitle}</p>{children}</div></main></div>;
}

export function LoginPage() {
  const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error,setError]=useState(''); const { login, enterDemo }=useAuth(); const navigate=useNavigate();
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{await login({email:String(data.get('email')),password:String(data.get('password'))});navigate('/app');}catch(err){setError(apiMessage(err));}finally{setBusy(false);}};
  return <AuthFrame title="Welcome back" subtitle="Sign in to continue where you left off."><form className="mt-8 space-y-5" onSubmit={submit}>{error&&<div role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700 dark:bg-rose-500/10 dark:text-rose-300">{error}</div>}<div><label className="label" htmlFor="email">Email address</label><input required type="email" id="email" name="email" className="input" placeholder="you@example.com" autoComplete="email"/></div><div><label className="label" htmlFor="password">Password</label><div className="relative"><input required minLength={8} type={show?'text':'password'} id="password" name="password" className="input pr-11" placeholder="Enter your password" autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-0 top-0 grid size-11 place-items-center text-slate-400" aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div><button disabled={busy} className="btn-primary w-full">{busy?<LoaderCircle className="animate-spin" size={17}/>:<>Sign in <ArrowRight size={17}/></>}</button></form><div className="my-6 flex items-center gap-3 text-xs text-slate-400 before:h-px before:flex-1 before:bg-slate-200 after:h-px after:flex-1 after:bg-slate-200">or</div><button onClick={()=>{enterDemo();navigate('/app');}} className="btn-secondary w-full">Explore demo workspace</button><p className="mt-7 text-center text-sm text-slate-500">New to StudyMate? <Link className="font-bold text-brand-600" to="/register">Create an account</Link></p></AuthFrame>;
}

export function RegisterPage() {
  const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const {register}=useAuth();const navigate=useNavigate();
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{await register({name:String(d.get('name')),email:String(d.get('email')),password:String(d.get('password')),course:String(d.get('course')||'')});navigate('/app');}catch(err){setError(apiMessage(err));}finally{setBusy(false);}};
  return <AuthFrame title="Create your workspace" subtitle="Start organizing your lessons and learning with purpose."><form className="mt-8 space-y-4" onSubmit={submit}>{error&&<div role="alert" className="rounded-xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div>}<div><label className="label" htmlFor="name">Full name</label><input required minLength={2} id="name" name="name" className="input" placeholder="Alex Morgan" autoComplete="name"/></div><div><label className="label" htmlFor="email">Email address</label><input required type="email" id="email" name="email" className="input" placeholder="you@example.com" autoComplete="email"/></div><div><label className="label" htmlFor="course">Course <span className="font-normal text-slate-400">(optional)</span></label><input id="course" name="course" className="input" placeholder="e.g. BS Information Technology"/></div><div><label className="label" htmlFor="password">Password</label><div className="relative"><input required minLength={8} maxLength={72} type={show?'text':'password'} id="password" name="password" className="input pr-11" placeholder="At least 8 characters" autoComplete="new-password"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-0 top-0 grid size-11 place-items-center text-slate-400" aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div><label className="flex gap-3 text-xs leading-5 text-slate-500"><span className="mt-0.5 grid size-4 shrink-0 place-items-center rounded bg-brand-600 text-white"><Check size={11}/></span><span>By creating an account, you agree to use StudyMate responsibly and keep your sign-in details secure.</span></label><button disabled={busy} className="btn-primary w-full">{busy?<LoaderCircle className="animate-spin" size={17}/>:<>Create free account <ArrowRight size={17}/></>}</button></form><p className="mt-7 text-center text-sm text-slate-500">Already have an account? <Link className="font-bold text-brand-600" to="/login">Sign in</Link></p></AuthFrame>;
}
