import { ArrowLeft, CheckCircle2, RotateCcw } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, apiMessage } from '../lib/api';
import { demoFlashcardDecks, saveDemoFlashcardDecks } from '../lib/demo';
import { useAuth } from '../store/AuthContext';
import type { ApiResponse, FlashcardDeckDetail } from '../types';

const intervals={again:'10 min',hard:'1 day',good:'3 days',easy:'7 days'} as const;
export function FlashcardStudyPage(){const {id=''}=useParams();const {isDemo}=useAuth();const [detail,setDetail]=useState<FlashcardDeckDetail|null>(null);const [index,setIndex]=useState(0);const [flipped,setFlipped]=useState(false);const [ratings,setRatings]=useState<Record<string,string>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{const load=async()=>{try{if(isDemo)setDetail(demoFlashcardDecks()[id]??null);else{const {data}=await api.get<ApiResponse<FlashcardDeckDetail>>(`/flashcard-decks/${id}`);setDetail(data.data);}}catch(e){setError(apiMessage(e));}finally{setLoading(false);}};void load();},[id,isDemo]);
  const [sessionStartedAt,setSessionStartedAt]=useState(()=>new Date().toISOString());const cards=useMemo(()=>detail?.cards??[],[detail]);const current=cards[index];const rate=async(rating:'again'|'hard'|'good'|'easy')=>{if(!current)return;try{if(isDemo){const all=demoFlashcardDecks();const card=all[id]?.cards.find(item=>item.id===current.id);if(card){card.last_rating=rating;card.review_count+=1;card.due_at=new Date(Date.now()+({again:10/60/24,hard:1,good:3,easy:7}[rating])*86400000).toISOString();saveDemoFlashcardDecks(all);}}else{await api.post(`/flashcards/${current.id}/review`,{rating});if(index===cards.length-1)await api.post(`/flashcard-decks/${id}/study-sessions`,{startedAt:sessionStartedAt}).catch(()=>undefined);}setRatings(previous=>({...previous,[current.id]:rating}));setFlipped(false);setIndex(value=>value+1);}catch(e){setError(apiMessage(e));}};
  if(loading)return <div className="grid min-h-[60vh] place-items-center"><span className="size-8 animate-spin rounded-full border-2 border-brand-200 border-t-brand-600"/></div>;if(!detail)return <div className="card p-10 text-center"><h1 className="font-display text-xl font-extrabold">Deck not found</h1><Link to="/app/flashcards" className="btn-primary mt-6">Back to flashcards</Link></div>;const complete=index>=cards.length;
  return <div className="mx-auto max-w-3xl"><Link to="/app/flashcards" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/>All decks</Link><div className="mt-6 flex items-end justify-between"><div><p className="eyebrow">Study session</p><h1 className="mt-2 font-display text-2xl font-extrabold">{detail.deck.title}</h1><p className="mt-1 text-sm text-slate-400">{detail.deck.lesson_title}</p></div><div className="text-right text-sm font-extrabold">{Math.min(index+1,cards.length)} <span className="text-slate-400">/ {cards.length}</span></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><div className="h-full rounded-full bg-violet-500 transition-all" style={{width:`${cards.length?Math.min(100,index/cards.length*100):0}%`}}/></div>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
    {complete?<div className="card mt-8 grid min-h-[430px] place-items-center p-8 text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><CheckCircle2 size={30}/></span><h2 className="mt-5 font-display text-2xl font-extrabold">Session complete</h2><p className="mt-2 text-sm text-slate-500">You reviewed {cards.length} cards. Their next review dates are now scheduled.</p><div className="mt-6 flex justify-center gap-2"><button onClick={()=>{setIndex(0);setRatings({});setFlipped(false);setSessionStartedAt(new Date().toISOString());}} className="btn-secondary"><RotateCcw size={16}/>Study again</button><Link to="/app/flashcards" className="btn-primary">Finish session</Link></div></div></div>:current&&<div className="mt-8"><button onClick={()=>setFlipped(!flipped)} className="card flex min-h-[390px] w-full flex-col items-center justify-center p-8 text-center transition hover:shadow-float" aria-label={flipped?'Show question':'Show answer'}><span className="rounded-full bg-violet-50 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-violet-600 dark:bg-violet-500/10 dark:text-violet-300">{current.topic??'Lesson'} · {current.difficulty}</span><p className="mt-8 text-xs font-extrabold uppercase tracking-[.18em] text-slate-400">{flipped?'Answer':'Question'}</p><div className="mt-4 max-w-2xl font-display text-2xl font-extrabold leading-relaxed sm:text-3xl">{flipped?current.back:current.front}</div><p className="mt-10 text-xs font-semibold text-slate-400">Tap the card to {flipped?'see the question':'reveal the answer'}</p></button>{flipped?<div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{(['again','hard','good','easy'] as const).map(rating=><button key={rating} onClick={()=>void rate(rating)} className={`rounded-xl border bg-white px-2 py-3 text-sm font-extrabold capitalize transition hover:-translate-y-0.5 dark:bg-slate-900 ${rating==='again'?'hover:border-rose-300 hover:text-rose-600':rating==='hard'?'hover:border-amber-300 hover:text-amber-600':rating==='good'?'hover:border-sky-300 hover:text-sky-600':'hover:border-emerald-300 hover:text-emerald-600'}`}>{rating}<span className="mt-1 block text-[10px] font-semibold text-slate-400">{intervals[rating]}</span></button>)}</div>:<button onClick={()=>setFlipped(true)} className="btn-primary mt-5 w-full">Show answer</button>}</div>}
    {Object.keys(ratings).length>0&&!complete&&<p className="mt-5 text-center text-xs font-semibold text-slate-400">{Object.keys(ratings).length} card{Object.keys(ratings).length===1?'':'s'} scheduled this session</p>}</div>}
