import { ArrowRight, BookOpen, Brain, CalendarClock, Layers3, Plus, Search, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, apiMessage } from '../lib/api';
import { demoFlashcardDecks } from '../lib/demo';
import { useAuth } from '../store/AuthContext';
import type { ApiResponse, FlashcardDeck } from '../types';

export function FlashcardsPage(){const {isDemo}=useAuth();const [decks,setDecks]=useState<FlashcardDeck[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');
  useEffect(()=>{const load=async()=>{try{if(isDemo)setDecks(Object.values(demoFlashcardDecks()).map(item=>item.deck));else{const {data}=await api.get<ApiResponse<FlashcardDeck[]>>('/flashcard-decks');setDecks(data.data);}}catch(e){setError(apiMessage(e));}finally{setLoading(false);}};void load();},[isDemo]);
  const filtered=useMemo(()=>decks.filter(deck=>`${deck.title} ${deck.lesson_title} ${deck.subject_name}`.toLowerCase().includes(query.toLowerCase())),[decks,query]);const total=decks.reduce((sum,deck)=>sum+deck.card_count,0);const due=decks.reduce((sum,deck)=>sum+(deck.due_count??deck.card_count),0);const metrics=[{icon:Layers3,label:'Total cards',value:total},{icon:CalendarClock,label:'Due for review',value:due},{icon:Brain,label:'Decks',value:decks.length}];
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Active recall</p><h1 className="mt-2 font-display text-3xl font-extrabold">Flashcards</h1><p className="mt-2 text-sm text-slate-500">Study saved decks and keep difficult concepts in rotation.</p></div><Link to="/app/subjects" className="btn-primary"><Plus size={17}/>Create from a lesson</Link></div><section className="mt-7 grid gap-4 sm:grid-cols-3">{metrics.map(({icon:Icon,label,value})=><div key={label} className="card flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-300"><Icon size={19}/></span><div><div className="text-xl font-extrabold">{value}</div><div className="text-xs font-semibold text-slate-400">{label}</div></div></div>)}</section><div className="relative mt-7 max-w-sm"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-10" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search flashcard decks..."/></div>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
    {loading?<div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(item=><div key={item} className="card h-48 animate-pulse bg-slate-100 dark:bg-slate-900"/>)}</div>:filtered.length?<div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(deck=>{const progress=deck.card_count?Math.round((deck.reviewed_count??0)/deck.card_count*100):0;return <article key={deck.id} className="card p-5"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-300"><BookOpen size={20}/></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-extrabold uppercase text-slate-500 dark:bg-slate-800">{deck.difficulty}</span></div><h2 className="mt-5 font-display text-lg font-extrabold">{deck.title}</h2><p className="mt-2 text-xs text-slate-400">{deck.lesson_title} · {deck.subject_name}</p><div className="mt-5"><div className="flex justify-between text-[11px] font-bold text-slate-400"><span>{deck.reviewed_count??0} of {deck.card_count} reviewed</span><span>{progress}%</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-violet-500" style={{width:`${progress}%`}}/></div></div><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-xs font-extrabold text-amber-600">{deck.due_count??deck.card_count} due</span><Link to={`/app/flashcards/${deck.id}/study`} className="flex items-center gap-1 text-xs font-extrabold text-brand-600">Study deck <ArrowRight size={14}/></Link></div></article>})}</div>:<div className="card mt-5 py-14 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-violet-50 text-violet-600"><Sparkles size={24}/></span><h2 className="mt-4 font-display text-lg font-extrabold">{query?'No matching decks':'Build your first flashcard deck'}</h2><p className="mt-2 text-sm text-slate-500">Open a processed lesson and generate cards grounded in its material.</p><Link to="/app/subjects" className="btn-primary mt-6">Browse lessons</Link></div>}
  </div>}
