import { ArrowLeft, BookOpen, CheckCircle2, Clock3, Download, Eye, FileText, Layers3, LoaderCircle, RefreshCw, ShieldCheck, Sparkles, Trash2, UploadCloud, X } from 'lucide-react';
import { useCallback, useEffect, useRef, useState, type DragEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Modal } from '../components/ui/Modal';
import { api, apiMessage } from '../lib/api';
import { demoDocuments, demoLessons, saveDemoDocuments } from '../lib/demo';
import { documentTone, extensionOf, formatBytes } from '../lib/files';
import { cn } from '../lib/utils';
import { useAuth } from '../store/AuthContext';
import type { ApiResponse, DocumentChunk, Lesson, StudyDocument } from '../types';

type ContentResponse = { document: StudyDocument; text: string; chunks: DocumentChunk[] };
const acceptedExtensions = ['pdf','docx','pptx','txt'];

function StatusBadge({ status }: { status: StudyDocument['status'] }) {
  const config = status === 'ready' ? ['Ready','bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300']
    : status === 'failed' ? ['Failed','bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300']
    : [status === 'uploading' ? 'Uploading' : 'Processing','bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300'];
  return <span className={cn('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide',config[1])}>{status==='ready'?<CheckCircle2 size={12}/>:status==='failed'?<X size={12}/>:<LoaderCircle size={12} className="animate-spin"/>}{config[0]}</span>;
}

export function LessonMaterialsPage() {
  const {id=''}=useParams(); const {isDemo}=useAuth(); const inputRef=useRef<HTMLInputElement>(null);
  const [lesson,setLesson]=useState<Lesson|null>(null); const [documents,setDocuments]=useState<StudyDocument[]>([]); const [selected,setSelected]=useState<File|null>(null); const [dragging,setDragging]=useState(false); const [uploading,setUploading]=useState(false); const [progress,setProgress]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [preview,setPreview]=useState<ContentResponse|null>(null); const [previewLoading,setPreviewLoading]=useState(false);
  const load=useCallback(async()=>{try{if(isDemo){const allLessons=Object.values(demoLessons()).flat();setLesson(allLessons.find(item=>item.id===id)??null);setDocuments(demoDocuments()[id]??[]);}else{const [lessonResponse,documentResponse]=await Promise.all([api.get<ApiResponse<Lesson>>(`/lessons/${id}`),api.get<ApiResponse<StudyDocument[]>>(`/lessons/${id}/documents`)]);setLesson(lessonResponse.data.data);setDocuments(documentResponse.data.data);}}catch(e){setError(apiMessage(e));}finally{setLoading(false);}},[id,isDemo]);
  useEffect(()=>{void load();},[load]);

  const choose=(file?:File)=>{setError('');if(!file)return;const extension=file.name.split('.').pop()?.toLowerCase();if(!acceptedExtensions.includes(extension??'')){setError('Choose a PDF, DOCX, PPTX, or TXT file.');return;}if(file.size>20*1024*1024){setError('The selected file exceeds the 20 MB limit.');return;}setSelected(file);};
  const drop=(event:DragEvent)=>{event.preventDefault();setDragging(false);choose(event.dataTransfer.files[0]);};
  const upload=async()=>{if(!selected)return;setUploading(true);setProgress(0);setError('');try{if(isDemo){for(const value of [18,42,67,86]){await new Promise(resolve=>setTimeout(resolve,150));setProgress(value);}const previewText=selected.name.toLowerCase().endsWith('.txt')?await selected.text():'Demo mode records this file locally. Sign in to process and extract text from Office and PDF documents.';const item:StudyDocument={id:crypto.randomUUID(),lesson_id:id,original_name:selected.name,mime_type:selected.type||'application/octet-stream',size_bytes:selected.size,status:'ready',error_message:null,chunk_count:Math.max(1,Math.ceil(selected.size/4800)),created_at:new Date().toISOString(),lesson_title:lesson?.title,subject_id:lesson?.subject_id,preview_text:previewText};const all=demoDocuments();all[id]=[item,...(all[id]??[])];saveDemoDocuments(all);setDocuments(all[id]);setProgress(100);}else{const form=new FormData();form.append('file',selected);const {data}=await api.post<ApiResponse<StudyDocument>>(`/lessons/${id}/documents`,form,{headers:{'Content-Type':'multipart/form-data'},onUploadProgress:event=>setProgress(event.total?Math.round(event.loaded/event.total*90):45)});setDocuments([data.data,...documents]);setProgress(100);}setSelected(null);if(inputRef.current)inputRef.current.value='';}catch(e){setError(apiMessage(e));}finally{setUploading(false);setTimeout(()=>setProgress(0),700);}};
  const view=async(document:StudyDocument)=>{setPreviewLoading(true);setError('');try{if(isDemo){setPreview({document,text:document.preview_text??'No text preview is available for this demo document.',chunks:[]});}else{const {data}=await api.get<ApiResponse<ContentResponse>>(`/documents/${document.id}/content`);setPreview(data.data);}}catch(e){setError(apiMessage(e));}finally{setPreviewLoading(false);}};
  const download=async(item:StudyDocument)=>{if(isDemo){setError('Original-file download requires a connected API workspace.');return;}try{const response=await api.get(`/documents/${item.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=window.document.createElement('a');anchor.href=url;anchor.download=item.original_name;anchor.click();URL.revokeObjectURL(url);}catch(e){setError(apiMessage(e));}};
  const remove=async(document:StudyDocument)=>{if(!confirm(`Delete ${document.original_name}?`))return;try{if(isDemo){const all=demoDocuments();all[id]=(all[id]??[]).filter(item=>item.id!==document.id);saveDemoDocuments(all);setDocuments(all[id]);}else{await api.delete(`/documents/${document.id}`);setDocuments(documents.filter(item=>item.id!==document.id));}}catch(e){setError(apiMessage(e));}};

  if(loading)return <div className="grid min-h-[60vh] place-items-center"><LoaderCircle className="animate-spin text-brand-600"/></div>;
  if(!lesson)return <div className="card p-10 text-center"><h1 className="font-display text-xl font-extrabold">Lesson not found</h1><Link to="/app/subjects" className="btn-primary mt-6">Back to subjects</Link></div>;
  const totalSize=documents.reduce((sum,item)=>sum+item.size_bytes,0);const totalChunks=documents.reduce((sum,item)=>sum+Number(item.chunk_count),0);
  const metrics = [
    { icon: FileText, label: 'Documents', value: documents.length },
    { icon: Layers3, label: 'Text chunks', value: totalChunks },
    { icon: Clock3, label: 'Storage used', value: formatBytes(totalSize) }
  ];
  return <div className="space-y-7"><div><Link to={`/app/subjects/${lesson.subject_id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900 dark:hover:text-white"><ArrowLeft size={16}/>Back to subject</Link><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Lesson materials</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-tight">{lesson.title}</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Upload source material once. StudyMate extracts and stores reusable text chunks.</p></div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300"><ShieldCheck size={15}/>Private to your account</span>{documents.some(item=>item.status==='ready')&&<Link to={`/app/lessons/${id}/study-tools`} className="btn-primary h-10"><Sparkles size={16}/>Open study tools</Link>}</div></div></div>
    <section className="grid gap-4 sm:grid-cols-3">{metrics.map(({icon:Icon,label,value})=><div className="card flex items-center gap-4 p-4" key={label}><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-300"><Icon size={19}/></span><div><div className="text-xl font-extrabold">{value}</div><div className="text-xs font-semibold text-slate-400">{label}</div></div></div>)}</section>
    <section className="card p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-lg font-extrabold">Add learning material</h2><p className="mt-1 text-xs text-slate-400">PDF, DOCX, PPTX, or TXT · maximum 20 MB</p></div><UploadCloud className="text-slate-300"/></div><input ref={inputRef} className="sr-only" type="file" accept=".pdf,.docx,.pptx,.txt" onChange={event=>choose(event.target.files?.[0])}/><button type="button" onClick={()=>inputRef.current?.click()} onDragOver={event=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={drop} className={cn('mt-5 flex min-h-40 w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed px-5 text-center transition',dragging?'border-brand-500 bg-brand-50 dark:bg-brand-500/10':'border-slate-200 bg-slate-50/70 hover:border-brand-300 hover:bg-brand-50/40 dark:border-slate-700 dark:bg-slate-950')}><span className="grid size-12 place-items-center rounded-2xl bg-white text-brand-600 shadow-sm dark:bg-slate-900"><UploadCloud size={23}/></span><span className="mt-4 text-sm font-extrabold">Drop a document here or browse</span><span className="mt-1 text-xs text-slate-400">The original file and extracted content are stored separately.</span></button>
      {selected&&<div className="mt-4 flex flex-col gap-3 rounded-xl border bg-white p-3.5 dark:bg-slate-900 sm:flex-row sm:items-center"><span className={cn('grid size-10 shrink-0 place-items-center rounded-xl text-[10px] font-extrabold',documentTone(selected.name))}>{extensionOf(selected.name)}</span><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{selected.name}</div><div className="mt-0.5 text-xs text-slate-400">{formatBytes(selected.size)}</div></div>{uploading?<div className="w-full sm:w-44"><div className="flex justify-between text-[10px] font-bold text-slate-400"><span>Uploading & processing</span><span>{progress}%</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-brand-600 transition-all" style={{width:`${progress}%`}}/></div></div>:<div className="flex gap-2"><button onClick={()=>setSelected(null)} className="btn-secondary h-9 px-3">Remove</button><button onClick={()=>void upload()} className="btn-primary h-9 px-3">Upload & process</button></div>}</div>}
      {error&&<div role="alert" className="mt-4 flex items-start justify-between gap-3 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700 dark:bg-rose-500/10 dark:text-rose-300"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss"><X size={16}/></button></div>}
    </section>
    <section><div className="flex items-end justify-between"><div><h2 className="font-display text-xl font-extrabold">Uploaded documents</h2><p className="mt-1 text-xs text-slate-400">Previously processed documents open without another extraction.</p></div><button onClick={()=>void load()} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Refresh documents"><RefreshCw size={16}/></button></div>{documents.length?<div className="mt-5 grid gap-3">{documents.map(item=><article className="card flex flex-col gap-4 p-4 sm:flex-row sm:items-center" key={item.id}><span className={cn('grid size-12 shrink-0 place-items-center rounded-xl text-[10px] font-extrabold',documentTone(item.original_name))}>{extensionOf(item.original_name)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-extrabold">{item.original_name}</h3><StatusBadge status={item.status}/></div><div className="mt-1.5 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400"><span>{formatBytes(item.size_bytes)}</span><span>{item.chunk_count} chunks</span><span>Added {new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(item.created_at))}</span></div>{item.error_message&&<p className="mt-2 text-xs font-semibold text-rose-600">{item.error_message}</p>}</div><div className="flex items-center gap-1 self-end sm:self-auto"><button disabled={item.status!=='ready'||previewLoading} onClick={()=>void view(item)} className="inline-flex h-9 items-center gap-2 rounded-lg px-3 text-xs font-bold text-slate-600 hover:bg-slate-100 disabled:opacity-40 dark:text-slate-300 dark:hover:bg-slate-800"><Eye size={15}/>Preview</button><button disabled={item.status!=='ready'} onClick={()=>void download(item)} className="grid size-9 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label={`Download ${item.original_name}`}><Download size={16}/></button><button onClick={()=>void remove(item)} className="grid size-9 place-items-center rounded-lg text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-500/10" aria-label={`Delete ${item.original_name}`}><Trash2 size={16}/></button></div></article>)}</div>:<div className="card mt-5 py-12 text-center"><BookOpen className="mx-auto text-slate-300" size={28}/><h3 className="mt-4 font-display font-extrabold">No materials yet</h3><p className="mt-2 text-sm text-slate-500">Upload the first source document for this lesson.</p></div>}</section>
    <Modal open={Boolean(preview)} onClose={()=>setPreview(null)} title={preview?.document.original_name??'Extracted text'} description={preview?`${preview.document.chunk_count} reusable chunks · extracted once`:undefined}>{preview&&<div><div className="max-h-[55vh] overflow-y-auto rounded-xl bg-slate-50 p-4 text-sm leading-7 text-slate-700 dark:bg-slate-950 dark:text-slate-300 scrollbar-thin whitespace-pre-wrap">{preview.text}</div><div className="mt-4 flex items-center justify-between text-xs text-slate-400"><span>Text is cleaned and ready for study-tool generation.</span><button onClick={()=>navigator.clipboard.writeText(preview.text)} className="font-extrabold text-brand-600">Copy text</button></div></div>}</Modal>
  </div>;
}
