import { ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, Check, FileUp, Menu, ShieldCheck, Sparkles, TimerReset } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Logo } from '../components/ui/Logo';
import { useAuth } from '../store/AuthContext';

export function LandingPage() {
  const { enterDemo } = useAuth(); const navigate = useNavigate();
  const demo = () => { enterDemo(); navigate('/app'); };
  return <div className="min-h-screen overflow-hidden bg-[#fbfcff] text-ink dark:bg-slate-950 dark:text-white">
    <header className="relative z-20 mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Logo/><nav className="hidden items-center gap-8 text-sm font-semibold text-slate-600 dark:text-slate-300 md:flex"><a href="#how">How it works</a><a href="#features">Features</a><a href="#roadmap">Roadmap</a></nav><div className="flex items-center gap-2"><Link to="/login" className="hidden px-4 py-2.5 text-sm font-bold text-slate-700 dark:text-slate-200 sm:block">Sign in</Link><Link to="/register" className="btn-primary">Get started <ArrowRight size={16}/></Link><button aria-label="Open menu" className="grid size-10 place-items-center md:hidden"><Menu size={22}/></button></div></header>
    <main>
      <section className="relative mx-auto max-w-7xl px-5 pb-24 pt-16 text-center sm:px-8 sm:pt-24 lg:pb-32">
        <div className="absolute left-1/2 top-20 -z-0 h-[450px] w-[650px] -translate-x-1/2 rounded-full bg-brand-200/25 blur-3xl dark:bg-brand-900/20"/>
        <div className="relative z-10 mx-auto max-w-4xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-brand-200 bg-white/80 px-3.5 py-2 text-xs font-extrabold text-brand-700 shadow-sm backdrop-blur dark:border-brand-900 dark:bg-slate-900/70 dark:text-brand-300"><Sparkles size={14}/> Study smarter with your own materials</div><h1 className="font-display text-4xl font-extrabold leading-[1.08] tracking-[-.045em] sm:text-6xl lg:text-7xl">Turn every lesson into a <span className="text-brand-600 dark:text-brand-400">clear path forward.</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-slate-600 dark:text-slate-300 sm:text-lg">Upload your notes, build focused study resources, test what you know, and understand exactly where to improve—all in one calm workspace.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/register" className="btn-primary h-12 px-6">Create your free workspace <ArrowRight size={17}/></Link><button onClick={demo} className="btn-secondary h-12 px-6">Explore the live demo</button></div><p className="mt-4 text-xs font-medium text-slate-400">No credit card · Built for students · Your materials stay yours</p></div>
        <div className="relative z-10 mx-auto mt-16 max-w-5xl rounded-[2rem] border bg-white/80 p-2 shadow-[0_30px_90px_rgba(49,46,129,.15)] backdrop-blur dark:bg-slate-900/70"><div className="overflow-hidden rounded-[1.5rem] border bg-slate-50 text-left dark:bg-slate-950"><div className="flex h-11 items-center gap-1.5 border-b bg-white px-4 dark:bg-slate-900"><span className="size-2.5 rounded-full bg-rose-400"/><span className="size-2.5 rounded-full bg-amber-400"/><span className="size-2.5 rounded-full bg-emerald-400"/><div className="mx-auto h-5 w-44 rounded-md bg-slate-100 dark:bg-slate-800"/></div><div className="grid min-h-[340px] grid-cols-[150px_1fr] sm:grid-cols-[190px_1fr]"><div className="border-r bg-white p-4 dark:bg-slate-900"><Logo compact/><div className="mt-7 space-y-2">{['Dashboard','Subjects','Reviewers','Flashcards','Quizzes'].map((item,i)=><div key={item} className={`h-8 rounded-lg px-3 py-2 text-[10px] font-bold ${i===0?'bg-brand-50 text-brand-700 dark:bg-brand-500/10':'text-slate-400'}`}>{item}</div>)}</div></div><div className="p-5 sm:p-7"><div className="h-5 w-40 rounded bg-slate-900 dark:bg-white"/><div className="mt-2 h-2 w-60 rounded bg-slate-200 dark:bg-slate-700"/><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['78%','Quiz accuracy'],['24','Lessons studied'],['182','Cards reviewed'],['7 days','Study streak']].map(([a,b])=><div key={b} className="rounded-xl border bg-white p-3 dark:bg-slate-900"><div className="text-lg font-extrabold">{a}</div><div className="mt-1 text-[9px] text-slate-400">{b}</div></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-[1.5fr_1fr]"><div className="h-36 rounded-xl border bg-white p-4 dark:bg-slate-900"><div className="h-2 w-24 rounded bg-slate-200 dark:bg-slate-700"/><div className="mt-5 flex h-20 items-end gap-2">{[35,55,42,70,58,84,72,90,76].map((h,i)=><span key={i} className="flex-1 rounded-t bg-brand-200 dark:bg-brand-700" style={{height:`${h}%`}}/>)}</div></div><div className="h-36 rounded-xl bg-brand-600 p-4 text-white"><div className="text-[9px] font-bold uppercase tracking-wider text-brand-200">Next best action</div><div className="mt-3 text-sm font-extrabold">Review Cryptography</div><div className="mt-2 text-[9px] leading-4 text-brand-100">Your recent quiz shows this topic needs another pass.</div></div></div></div></div></div></div>
      </section>
      <section id="how" className="border-y bg-white py-24 dark:bg-slate-900"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">One connected flow</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">From source material to real progress</h2><p className="mt-4 text-slate-500 dark:text-slate-400">StudyMate keeps generation, practice, and analytics connected so each session informs the next.</p></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[[FileUp,'Bring your materials','Organize PDF, DOCX, PPTX, and text files by subject and lesson.'],[BrainCircuit,'Create focused resources','Generate grounded reviewers, flashcards, and quizzes from your own content.'],[BarChart3,'See what needs work','Track topic-level accuracy and get clear, rule-based next actions.']].map(([Icon,title,copy],i)=><article key={title as string} className="relative rounded-2xl border p-7"><span className="mb-6 grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-300"><Icon size={21}/></span><span className="absolute right-6 top-7 text-sm font-extrabold text-slate-200 dark:text-slate-700">0{i+1}</span><h3 className="font-display text-lg font-extrabold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{copy as string}</p></article>)}</div></div></section>
      <section id="features" className="mx-auto max-w-6xl px-5 py-24 sm:px-8"><div className="grid items-center gap-14 lg:grid-cols-2"><div><p className="eyebrow">Designed for focused study</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">Useful AI, grounded in your lesson.</h2><p className="mt-5 leading-7 text-slate-500 dark:text-slate-400">AI handles the generative work. Scoring, progress, weak-topic detection, and study priorities stay transparent and deterministic.</p><div className="mt-8 space-y-4">{['Answers are constrained to uploaded lesson context','Generated resources are saved—no wasteful repeat calls','Original-wording mode preserves exact source sentences','Configurable limits keep free-tier usage predictable'].map(item=><div key={item} className="flex gap-3 text-sm font-semibold text-slate-700 dark:text-slate-200"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><Check size={14}/></span>{item}</div>)}</div></div><div className="grid gap-4 sm:grid-cols-2">{[[BookOpenCheck,'Study resources','Reviewers and summaries that stay tied to source lessons.'],[TimerReset,'Active recall','Flashcard scheduling and configurable practice quizzes.'],[ShieldCheck,'Private by design','Keys stay server-side and every resource is ownership-checked.'],[BarChart3,'Actionable progress','Topic accuracy becomes a concrete recommendation.']].map(([Icon,title,copy])=><div key={title as string} className="card p-6"><Icon className="text-brand-600 dark:text-brand-400" size={22}/><h3 className="mt-5 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{copy as string}</p></div>)}</div></div></section>
    </main>
    <footer className="border-t bg-white py-8 dark:bg-slate-900"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 text-sm text-slate-400 sm:flex-row sm:px-8"><Logo/><span>© 2026 StudyMate AI. Built for better study habits.</span></div></footer>
  </div>;
}
