import { ArrowRight, FileText, FolderOpen, Layers3, Search, UploadCloud } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, apiMessage } from '../lib/api';
import { demoDocuments } from '../lib/demo';
import { documentTone, extensionOf, formatBytes } from '../lib/files';
import { cn } from '../lib/utils';
import { useAuth } from '../store/AuthContext';
import type { ApiResponse, StudyDocument } from '../types';

export function MaterialsPage() {
  const {isDemo}=useAuth();const [documents,setDocuments]=useState<StudyDocument[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');
  useEffect(()=>{const load=async()=>{try{if(isDemo)setDocuments(Object.values(demoDocuments()).flat().sort((a,b)=>b.created_at.localeCompare(a.created_at)));else{const {data}=await api.get<ApiResponse<StudyDocument[]>>('/documents');setDocuments(data.data);}}catch(e){setError(apiMessage(e));}finally{setLoading(false);}};void load();},[isDemo]);
  const filtered=useMemo(()=>documents.filter(item=>`${item.original_name} ${item.lesson_title} ${item.subject_name}`.toLowerCase().includes(query.toLowerCase())),[documents,query]);
  const ready=documents.filter(item=>item.status==='ready').length;const chunks=documents.reduce((sum,item)=>sum+Number(item.chunk_count),0);
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Source library</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-tight">Study materials</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Every uploaded source, organized by subject and lesson.</p></div><Link to="/app/subjects" className="btn-primary"><UploadCloud size={17}/>Choose a lesson to upload</Link></div>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="text-2xl font-extrabold">{documents.length}</div><div className="mt-1 text-xs font-semibold text-slate-400">Total documents</div></div><div className="card p-5"><div className="text-2xl font-extrabold">{ready}</div><div className="mt-1 text-xs font-semibold text-slate-400">Ready to study</div></div><div className="card p-5"><div className="text-2xl font-extrabold">{chunks}</div><div className="mt-1 text-xs font-semibold text-slate-400">Searchable text chunks</div></div></section>
    <div className="mt-7 relative max-w-sm"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-10" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search files, lessons, subjects..."/></div>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
    {loading?<div className="mt-5 space-y-3">{[1,2,3].map(item=><div key={item} className="card h-24 animate-pulse bg-slate-100 dark:bg-slate-900"/>)}</div>:filtered.length?<div className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-card dark:bg-slate-900"><div className="hidden grid-cols-[1.5fr_1fr_1fr_100px_50px] gap-4 border-b bg-slate-50 px-5 py-3 text-[10px] font-extrabold uppercase tracking-wider text-slate-400 dark:bg-slate-950 md:grid"><span>Document</span><span>Lesson</span><span>Subject</span><span>Size</span><span/></div><div className="divide-y">{filtered.map(item=><div key={item.id} className="grid gap-4 p-4 transition hover:bg-slate-50/70 dark:hover:bg-slate-800/40 md:grid-cols-[1.5fr_1fr_1fr_100px_50px] md:items-center md:px-5"><div className="flex min-w-0 items-center gap-3"><span className={cn('grid size-10 shrink-0 place-items-center rounded-xl text-[9px] font-extrabold',documentTone(item.original_name))}>{extensionOf(item.original_name)}</span><div className="min-w-0"><div className="truncate text-sm font-extrabold">{item.original_name}</div><div className="mt-1 flex items-center gap-1 text-[11px] text-slate-400"><Layers3 size={12}/>{item.chunk_count} chunks</div></div></div><div className="text-sm font-semibold text-slate-600 dark:text-slate-300"><span className="mr-2 text-[10px] uppercase text-slate-400 md:hidden">Lesson</span>{item.lesson_title??'Lesson'}</div><div className="text-sm text-slate-500"><span className="mr-2 text-[10px] uppercase text-slate-400 md:hidden">Subject</span>{item.subject_name??'Subject'}</div><div className="text-xs font-semibold text-slate-400">{formatBytes(item.size_bytes)}</div><Link to={`/app/lessons/${item.lesson_id}`} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-brand-50 hover:text-brand-600" aria-label={`Open ${item.original_name}`}><ArrowRight size={16}/></Link></div>)}</div></div>:<div className="card mt-5 flex flex-col items-center py-14 text-center"><span className="grid size-14 place-items-center rounded-2xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><FolderOpen size={25}/></span><h2 className="mt-5 font-display text-lg font-extrabold">{query?'No matching materials':'Your material library is empty'}</h2><p className="mt-2 max-w-sm text-sm text-slate-500">{query?'Try a different search.':'Open a lesson to upload PDF, DOCX, PPTX, or TXT source material.'}</p>{!query&&<Link to="/app/subjects" className="btn-primary mt-6"><FileText size={16}/>Browse subjects</Link>}</div>}
  </div>;
}
