import { ArrowRight, BarChart3, FileQuestion, GraduationCap, Plus, Search, Sparkles, Target } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, apiMessage } from '../lib/api';
import { demoQuizzes } from '../lib/demo';
import { useAuth } from '../store/AuthContext';
import type { ApiResponse, QuizSummary } from '../types';

export function QuizzesPage(){const {isDemo}=useAuth();const [quizzes,setQuizzes]=useState<QuizSummary[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');
  useEffect(()=>{const load=async()=>{try{if(isDemo)setQuizzes(Object.values(demoQuizzes()).map(item=>item.quiz));else{const {data}=await api.get<ApiResponse<QuizSummary[]>>('/quizzes');setQuizzes(data.data);}}catch(e){setError(apiMessage(e));}finally{setLoading(false);}};void load();},[isDemo]);
  const filtered=useMemo(()=>quizzes.filter(quiz=>`${quiz.title} ${quiz.lesson_title} ${quiz.subject_name}`.toLowerCase().includes(query.toLowerCase())),[quizzes,query]);const attempts=quizzes.reduce((sum,quiz)=>sum+(quiz.attempt_count??0),0);const scored=quizzes.filter(quiz=>quiz.best_percentage!=null);const average=scored.length?Math.round(scored.reduce((sum,quiz)=>sum+(quiz.best_percentage??0),0)/scored.length):0;const metrics=[{icon:FileQuestion,label:'Saved quizzes',value:quizzes.length},{icon:Target,label:'Attempts completed',value:attempts},{icon:BarChart3,label:'Average best score',value:`${average}%`}];
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Practice and measure</p><h1 className="mt-2 font-display text-3xl font-extrabold">Quizzes</h1><p className="mt-2 text-sm text-slate-500">Take saved quizzes and review every answer without another AI call.</p></div><Link to="/app/subjects" className="btn-primary"><Plus size={17}/>Create from a lesson</Link></div><section className="mt-7 grid gap-4 sm:grid-cols-3">{metrics.map(({icon:Icon,label,value})=><div key={label} className="card flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-600 dark:bg-sky-500/10 dark:text-sky-300"><Icon size={19}/></span><div><div className="text-xl font-extrabold">{value}</div><div className="text-xs font-semibold text-slate-400">{label}</div></div></div>)}</section><div className="relative mt-7 max-w-sm"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-10" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search quizzes..."/></div>{error&&<div role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
    {loading?<div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(item=><div key={item} className="card h-52 animate-pulse bg-slate-100 dark:bg-slate-900"/>)}</div>:filtered.length?<div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(quiz=><article key={quiz.id} className="card p-5"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-sky-50 text-sky-600 dark:bg-sky-500/10 dark:text-sky-300"><GraduationCap size={21}/></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-extrabold uppercase text-slate-500 dark:bg-slate-800">{quiz.difficulty}</span></div><h2 className="mt-5 font-display text-lg font-extrabold">{quiz.title}</h2><p className="mt-2 text-xs text-slate-400">{quiz.lesson_title} · {quiz.subject_name}</p><div className="mt-5 grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3 text-center dark:bg-slate-800/60"><div><strong className="block text-sm">{quiz.question_count}</strong><span className="text-[10px] text-slate-400">Questions</span></div><div><strong className="block text-sm">{quiz.attempt_count??0}</strong><span className="text-[10px] text-slate-400">Attempts</span></div><div><strong className="block text-sm">{quiz.best_percentage==null?'—':`${Math.round(quiz.best_percentage)}%`}</strong><span className="text-[10px] text-slate-400">Best</span></div></div><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-[10px] font-extrabold uppercase tracking-wide text-slate-400">{quiz.question_type.replaceAll('_',' ')}</span><Link to={`/app/quizzes/${quiz.id}/take`} className="flex items-center gap-1 text-xs font-extrabold text-brand-600">Start quiz <ArrowRight size={14}/></Link></div></article>)}</div>:<div className="card mt-5 py-14 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-sky-50 text-sky-600"><Sparkles size={24}/></span><h2 className="mt-4 font-display text-lg font-extrabold">{query?'No matching quizzes':'Create your first practice quiz'}</h2><p className="mt-2 text-sm text-slate-500">Open a processed lesson and generate questions grounded in its material.</p><Link to="/app/subjects" className="btn-primary mt-6">Browse lessons</Link></div>}
  </div>}
