import { ArrowRight, BookCopy, FileText, Search, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, apiMessage } from '../lib/api';
import { demoReviewers, demoSummaries } from '../lib/demo';
import { useAuth } from '../store/AuthContext';
import type { ApiResponse, ReviewerResource, SummaryResource } from '../types';

type ResourceItem={id:string;lesson_id:string;title:string;kind:'Reviewer'|'Summary';style:string;meta:string;lesson?:string;subject?:string;updated:string};

export function ResourcesPage(){
  const {isDemo}=useAuth();const [reviewers,setReviewers]=useState<ReviewerResource[]>([]);const [summaries,setSummaries]=useState<SummaryResource[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');
  useEffect(()=>{const load=async()=>{try{if(isDemo){setReviewers(demoReviewers());setSummaries(demoSummaries());}else{const [reviewerResponse,summaryResponse]=await Promise.all([api.get<ApiResponse<ReviewerResource[]>>('/reviewers'),api.get<ApiResponse<SummaryResource[]>>('/summaries')]);setReviewers(reviewerResponse.data.data);setSummaries(summaryResponse.data.data);}}catch(e){setError(apiMessage(e));}finally{setLoading(false);}};void load();},[isDemo]);
  const items=useMemo<ResourceItem[]>(()=>[...reviewers.map(item=>({id:item.id,lesson_id:item.lesson_id,title:item.title,kind:'Reviewer' as const,style:'bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-300',meta:`${item.reviewer_type.replace('_',' ')} · ${item.difficulty}`,lesson:item.lesson_title,subject:item.subject_name,updated:item.updated_at})),...summaries.map(item=>({id:item.id,lesson_id:item.lesson_id,title:item.title,kind:'Summary' as const,style:'bg-sky-50 text-sky-600 dark:bg-sky-500/10 dark:text-sky-300',meta:`${item.summary_length} summary`,lesson:item.lesson_title,subject:item.subject_name,updated:item.updated_at}))].filter(item=>`${item.title} ${item.lesson} ${item.subject}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updated.localeCompare(a.updated)),[reviewers,summaries,query]);
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Saved study resources</p><h1 className="mt-2 font-display text-3xl font-extrabold">Reviewers & summaries</h1><p className="mt-2 text-sm text-slate-500">Generated once, saved here, and reopened without another AI request.</p></div><Link to="/app/subjects" className="btn-primary"><Sparkles size={17}/>Choose a lesson</Link></div><section className="mt-7 grid gap-4 sm:grid-cols-2"><div className="card flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><BookCopy size={20}/></span><div><div className="text-2xl font-extrabold">{reviewers.length}</div><div className="text-xs font-semibold text-slate-400">Saved reviewers</div></div></div><div className="card flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-xl bg-sky-50 text-sky-600 dark:bg-sky-500/10"><FileText size={20}/></span><div><div className="text-2xl font-extrabold">{summaries.length}</div><div className="text-xs font-semibold text-slate-400">Saved summaries</div></div></div></section><div className="relative mt-7 max-w-sm"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="input pl-10" placeholder="Search saved resources..."/></div>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
    {loading?<div className="mt-5 grid gap-4 sm:grid-cols-2">{[1,2,3,4].map(item=><div key={item} className="card h-36 animate-pulse bg-slate-100 dark:bg-slate-900"/>)}</div>:items.length?<div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={`${item.kind}-${item.id}`} className="card p-5"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-xl ${item.style}`}>{item.kind==='Reviewer'?<BookCopy size={18}/>:<FileText size={18}/>}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide text-slate-500 dark:bg-slate-800">{item.kind}</span></div><h2 className="mt-5 line-clamp-2 font-display font-extrabold">{item.title}</h2><p className="mt-2 text-xs capitalize text-slate-400">{item.meta}</p><div className="mt-5 border-t pt-4"><div className="text-xs font-bold text-slate-600 dark:text-slate-300">{item.lesson??'Lesson'}</div><div className="mt-1 text-[11px] text-slate-400">{item.subject??'Subject'}</div><Link to={`/app/lessons/${item.lesson_id}/study-tools`} className="mt-4 flex items-center justify-between text-xs font-extrabold text-brand-600">Open resource <ArrowRight size={14}/></Link></div></article>)}</div>:<div className="card mt-5 py-14 text-center"><BookCopy className="mx-auto text-slate-300" size={28}/><h2 className="mt-4 font-display text-lg font-extrabold">{query?'No matching resources':'No saved resources yet'}</h2><p className="mt-2 text-sm text-slate-500">Generate a reviewer or summary from a lesson to see it here.</p><Link to="/app/subjects" className="btn-primary mt-6">Browse lessons</Link></div>}
  </div>;
}
