import { Archive, ArrowRight, BookOpen, MoreHorizontal, Plus, Search, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Modal } from '../components/ui/Modal';
import { SubjectIcon } from '../components/SubjectIcon';
import { api, apiMessage } from '../lib/api';
import { demoSubjects, saveDemoSubjects } from '../lib/demo';
import { useAuth } from '../store/AuthContext';
import type { ApiResponse, Subject, SubjectColor } from '../types';

export function SubjectsPage() {
  const { isDemo }=useAuth(); const [subjects,setSubjects]=useState<Subject[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [open,setOpen]=useState(false); const [error,setError]=useState(''); const [menu,setMenu]=useState<string|null>(null);
  const load=async()=>{setLoading(true);setError('');try{if(isDemo)setSubjects(demoSubjects());else{const {data}=await api.get<ApiResponse<Subject[]>>('/subjects');setSubjects(data.data);}}catch(e){setError(apiMessage(e));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>subjects.filter(s=>`${s.name} ${s.description}`.toLowerCase().includes(query.toLowerCase())),[subjects,query]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const input={name:String(d.get('name')),description:String(d.get('description')),icon:String(d.get('icon')),color:String(d.get('color')) as SubjectColor};try{if(isDemo){const next=[{id:crypto.randomUUID(),...input,lesson_count:0},...subjects];saveDemoSubjects(next);setSubjects(next);}else{const {data}=await api.post<ApiResponse<Subject>>('/subjects',input);setSubjects([data.data,...subjects]);}setOpen(false);}catch(err){setError(apiMessage(err));}};
  const remove=async(id:string)=>{if(!confirm('Delete this subject and all its lessons? This cannot be undone.'))return;try{if(isDemo){const next=subjects.filter(s=>s.id!==id);saveDemoSubjects(next);setSubjects(next);}else{await api.delete(`/subjects/${id}`);setSubjects(subjects.filter(s=>s.id!==id));}}catch(e){setError(apiMessage(e));}setMenu(null);};
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Your learning library</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-tight">Subjects</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Keep every course organized into focused, manageable lessons.</p></div><button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/>New subject</button></div>
    <div className="mt-7 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full max-w-sm"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input pl-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search subjects..."/></div><p className="text-xs font-semibold text-slate-400">{subjects.length} active subject{subjects.length===1?'':'s'}</p></div>
    {error&&<div role="alert" className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700 dark:bg-rose-500/10 dark:text-rose-300">{error}</div>}
    {loading?<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map(i=><div key={i} className="card h-56 animate-pulse bg-slate-100 dark:bg-slate-900"/>)}</div>:filtered.length?<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(subject=><article className="card group relative p-5 transition hover:-translate-y-0.5 hover:shadow-float" key={subject.id}><div className="flex items-start justify-between"><SubjectIcon icon={subject.icon} color={subject.color}/><div className="relative"><button className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label={`Options for ${subject.name}`} onClick={()=>setMenu(menu===subject.id?null:subject.id)}><MoreHorizontal size={18}/></button>{menu===subject.id&&<div className="absolute right-0 top-10 z-10 w-40 rounded-xl border bg-white p-1.5 text-sm shadow-float dark:bg-slate-900"><button className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left hover:bg-slate-50 dark:hover:bg-slate-800"><Archive size={15}/>Archive</button><button onClick={()=>void remove(subject.id)} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-500/10"><Trash2 size={15}/>Delete</button></div>}</div></div><h2 className="mt-5 font-display text-lg font-extrabold">{subject.name}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500 dark:text-slate-400">{subject.description||'No description yet.'}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="flex items-center gap-2 text-xs font-bold text-slate-400"><BookOpen size={15}/>{subject.lesson_count} lesson{subject.lesson_count===1?'':'s'}</span><Link to={`/app/subjects/${subject.id}`} className="flex items-center gap-1 text-xs font-extrabold text-brand-600">Open <ArrowRight size={14}/></Link></div></article>)}</div>:<div className="card mt-6 flex flex-col items-center py-16 text-center"><SubjectIcon icon="book-open" color="indigo" className="size-14"/><h2 className="mt-5 font-display text-lg font-extrabold">{query?'No matching subjects':'Create your first subject'}</h2><p className="mt-2 max-w-sm text-sm text-slate-500">{query?'Try a different search term.':'Subjects are the home for your lessons, files, reviewers, flashcards, and quizzes.'}</p>{!query&&<button onClick={()=>setOpen(true)} className="btn-primary mt-6"><Plus size={17}/>Create subject</button>}</div>}
    <Modal open={open} onClose={()=>setOpen(false)} title="Create a new subject" description="You can change these details at any time."><form onSubmit={create} className="space-y-4"><div><label className="label" htmlFor="subject-name">Subject name</label><input autoFocus required minLength={2} id="subject-name" name="name" className="input" placeholder="e.g. Network Security"/></div><div><label className="label" htmlFor="subject-description">Description <span className="font-normal text-slate-400">(optional)</span></label><textarea id="subject-description" name="description" className="input h-24 resize-none py-3" placeholder="What are you learning in this subject?"/></div><div className="grid grid-cols-2 gap-3"><div><label className="label" htmlFor="subject-icon">Icon</label><select id="subject-icon" name="icon" className="input"><option value="book-open">Book</option><option value="shield">Shield</option><option value="code">Code</option><option value="science">Science</option><option value="scale">Ethics</option><option value="sparkles">Creative</option></select></div><div><label className="label" htmlFor="subject-color">Color</label><select id="subject-color" name="color" className="input"><option value="indigo">Indigo</option><option value="violet">Violet</option><option value="sky">Sky</option><option value="emerald">Emerald</option><option value="amber">Amber</option><option value="rose">Rose</option></select></div></div><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">Cancel</button><button className="btn-primary">Create subject</button></div></form></Modal>
  </div>;
}
