import { randomUUID } from 'node:crypto';
import type { RowDataPacket } from 'mysql2';
import { db } from '../config/database.js';

export type PlanEventType='exam'|'quiz'|'assignment'|'deadline';
export type TaskType='review'|'flashcards'|'quiz'|'tutor'|'practice_exam';
export interface LessonSignal {id:string;title:string;subject_id:string;subject_name:string;processing_status:string;accuracy:number|null;weak_topic_count:number;weak_topics:string[]}
export interface TaskInput {lessonId:string|null;title:string;taskType:TaskType;rationale:string;estimatedMinutes:number;priority:number;position:number;dueAt:Date}

export const listPlans=async(userId:string)=>{const [rows]=await db.query<(RowDataPacket&{id:string;subject_id:string|null;subject_name:string|null;title:string;event_type:PlanEventType;due_at:Date;coverage:string|null;notes:string|null;created_at:Date;updated_at:Date;task_count:number;completed_count:number;next_task_due:Date|null;lesson_count:number})[]>(`SELECT p.*,s.name subject_name,COUNT(DISTINCT t.id) task_count,COUNT(DISTINCT CASE WHEN t.completed_at IS NOT NULL THEN t.id END) completed_count,MIN(CASE WHEN t.completed_at IS NULL THEN t.due_at END) next_task_due,COUNT(DISTINCT pl.lesson_id) lesson_count FROM study_plans p LEFT JOIN subjects s ON s.id=p.subject_id LEFT JOIN study_tasks t ON t.plan_id=p.id LEFT JOIN study_plan_lessons pl ON pl.plan_id=p.id WHERE p.user_id=? GROUP BY p.id,s.name ORDER BY p.due_at`,[userId]);return rows.map(row=>({...row,task_count:Number(row.task_count),completed_count:Number(row.completed_count),lesson_count:Number(row.lesson_count)}));};

export const findPlan=async(id:string,userId:string)=>{const [rows]=await db.query<(RowDataPacket&{id:string;user_id:string;subject_id:string|null;subject_name:string|null;title:string;event_type:PlanEventType;due_at:Date;coverage:string|null;notes:string|null;created_at:Date;updated_at:Date})[]>(`SELECT p.*,s.name subject_name FROM study_plans p LEFT JOIN subjects s ON s.id=p.subject_id WHERE p.id=? AND p.user_id=? LIMIT 1`,[id,userId]);return rows[0]??null;};

export const getPlanLessonIds=async(planId:string)=>{const [rows]=await db.query<(RowDataPacket&{lesson_id:string})[]>('SELECT lesson_id FROM study_plan_lessons WHERE plan_id=? ORDER BY lesson_id',[planId]);return rows.map(row=>row.lesson_id);};

export const getTasks=async(planId:string)=>{const [rows]=await db.query<(RowDataPacket&{id:string;plan_id:string;lesson_id:string|null;lesson_title:string|null;title:string;task_type:TaskType;rationale:string;estimated_minutes:number;priority:number;position:number;due_at:Date;completed_at:Date|null})[]>(`SELECT t.*,l.title lesson_title FROM study_tasks t LEFT JOIN lessons l ON l.id=t.lesson_id WHERE t.plan_id=? ORDER BY t.completed_at IS NOT NULL,t.due_at,t.position`,[planId]);return rows.map(row=>({...row,estimated_minutes:Number(row.estimated_minutes),priority:Number(row.priority),position:Number(row.position)}));};

export const getLessonSignals=async(userId:string,subjectId:string,lessonIds:string[])=>{if(!lessonIds.length)return[];const placeholders=lessonIds.map(()=>'?').join(',');const [rows]=await db.query<(RowDataPacket&{id:string;title:string;subject_id:string;subject_name:string;processing_status:string;accuracy:number|null;weak_topic_count:number;weak_topics:string|null})[]>(`SELECT l.id,l.title,l.subject_id,s.name subject_name,l.processing_status,CASE WHEN SUM(COALESCE(tp.total_answers,0))=0 THEN NULL ELSE ROUND(SUM(tp.correct_answers)/SUM(tp.total_answers)*100,2) END accuracy,SUM(CASE WHEN tp.total_answers>0 AND tp.correct_answers/tp.total_answers<0.6 THEN 1 ELSE 0 END) weak_topic_count,GROUP_CONCAT(CASE WHEN tp.total_answers>0 AND tp.correct_answers/tp.total_answers<0.6 THEN t.name END ORDER BY t.name SEPARATOR '||') weak_topics FROM lessons l JOIN subjects s ON s.id=l.subject_id LEFT JOIN topics t ON t.lesson_id=l.id LEFT JOIN topic_performance tp ON tp.topic_id=t.id AND tp.user_id=? WHERE s.user_id=? AND s.id=? AND l.id IN (${placeholders}) GROUP BY l.id,l.title,l.subject_id,s.name,l.processing_status`,[userId,userId,subjectId,...lessonIds]);return rows.map(row=>({...row,accuracy:row.accuracy===null?null:Number(row.accuracy),weak_topic_count:Number(row.weak_topic_count),weak_topics:row.weak_topics?row.weak_topics.split('||'):[]}));};

export const insertPlan=async(input:{id:string;userId:string;subjectId:string;title:string;eventType:PlanEventType;dueAt:Date;coverage:string|null;notes:string|null;lessonIds:string[];tasks:TaskInput[]})=>{const connection=await db.getConnection();try{await connection.beginTransaction();await connection.execute(`INSERT INTO study_plans (id,user_id,subject_id,title,event_type,due_at,coverage,notes) VALUES (?,?,?,?,?,?,?,?)`,[input.id,input.userId,input.subjectId,input.title,input.eventType,input.dueAt,input.coverage,input.notes]);for(const lessonId of input.lessonIds)await connection.execute('INSERT INTO study_plan_lessons (plan_id,lesson_id) VALUES (?,?)',[input.id,lessonId]);for(const task of input.tasks)await connection.execute(`INSERT INTO study_tasks (id,plan_id,lesson_id,title,task_type,rationale,estimated_minutes,priority,position,due_at) VALUES (?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),input.id,task.lessonId,task.title,task.taskType,task.rationale,task.estimatedMinutes,task.priority,task.position,task.dueAt]);await connection.commit();}catch(error){await connection.rollback();throw error;}finally{connection.release();}};

export const replacePendingTasks=async(planId:string,tasks:TaskInput[])=>{const connection=await db.getConnection();try{await connection.beginTransaction();await connection.execute('DELETE FROM study_tasks WHERE plan_id=? AND completed_at IS NULL',[planId]);for(const task of tasks)await connection.execute(`INSERT INTO study_tasks (id,plan_id,lesson_id,title,task_type,rationale,estimated_minutes,priority,position,due_at) VALUES (?,?,?,?,?,?,?,?,?,?)`,[randomUUID(),planId,task.lessonId,task.title,task.taskType,task.rationale,task.estimatedMinutes,task.priority,task.position,task.dueAt]);await connection.execute('UPDATE study_plans SET updated_at=CURRENT_TIMESTAMP WHERE id=?',[planId]);await connection.commit();}catch(error){await connection.rollback();throw error;}finally{connection.release();}};

export const setTaskCompleted=async(input:{planId:string;taskId:string;userId:string;completed:boolean})=>{const [result]=await db.execute(`UPDATE study_tasks t JOIN study_plans p ON p.id=t.plan_id SET t.completed_at=? WHERE t.id=? AND t.plan_id=? AND p.user_id=?`,[input.completed?new Date():null,input.taskId,input.planId,input.userId]);return 'affectedRows' in result&&result.affectedRows>0;};
export const deletePlan=async(id:string,userId:string)=>{const [result]=await db.execute('DELETE FROM study_plans WHERE id=? AND user_id=?',[id,userId]);return 'affectedRows' in result&&result.affectedRows>0;};
